<?php

/**
 * Generated by ZF2ModuleCreator
 */
namespace Users;

use Zend\Router\Http\Segment;
use Zend\ServiceManager\Factory\InvokableFactory;

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'users' => array(
                'type' => Segment::class,
                'options' => array(
                    'route'    => '/users[/:action][/:id]',
                    'constraints' => array(
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id'     => '[0-9]+',
                    ),

                    'defaults' => array(
                        'controller' => Controller\UsersController::class,
                        'action' => 'index',
                    )
                )
            )
        )

    )
);