<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace Users;

use Zend\Db\Adapter\AdapterInterface;
use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;
use Album\Model\Album;
use Album\Model\AlbumTable;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\ServiceManager\Config;


class Module implements ConfigProviderInterface
{


    public function getServiceConfig()
    {
    }

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '../../config/module.config.php';
    }

    public function getControllerConfig()
    {
		return [
			'factories' => [
				Controller\UsersController::class => function($container) {
					$dbAdapter = $container->get(AdapterInterface::class);
					return new Controller\UsersController($dbAdapter);
				},
			],
		];
    }



}